<?php


namespace app\client\controller;


use app\models\Redis;
use think\Controller;

class Base extends Controller
{
    protected $uid;
    protected $openid;

    protected function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
        $token = request()->get('token');
        $redis_model = new Redis();
        $data = $redis_model->get($token);
        if(!$data){
            $this->redirect('https://www.baidu.com/');
        }
        $data = json_decode($data,true);
        $this->uid = $data['uid'];
        $this->openid = $data['openid'];
    }
}